# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(952, 700))
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 350, 701, 421))
        self.tableView.setStyleSheet("color: rgb(0, 0, 0); background: rgb(189, 189, 189)")
        self.tableView.setWordWrap(True)
        self.tableView.setObjectName("tableView")
        self.searchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchBar.setGeometry(QtCore.QRect(10, 310, 381, 20))
        self.searchBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.searchBar.setText("")
        self.searchBar.setObjectName("searchBar")
        self.filterButtonSpecials = QtWidgets.QPushButton(self.centralwidget)
        self.filterButtonSpecials.setGeometry(QtCore.QRect(760, 650, 300, 100))
        self.filterButtonSpecials.setStyleSheet("color: rgb(255, 255, 255);")
        self.filterButtonSpecials.setObjectName("filterButtonSpecials")
        self.filterButtonScore = QtWidgets.QPushButton(self.centralwidget)
        self.filterButtonScore.setGeometry(QtCore.QRect(760, 370, 300, 100))
        self.filterButtonScore.setStyleSheet("color: rgb(255, 255, 255);")
        self.filterButtonScore.setObjectName("filterButtonScore")
        self.filterValveGames = QtWidgets.QPushButton(self.centralwidget)
        self.filterValveGames.setGeometry(QtCore.QRect(760, 510, 300, 100))
        self.filterValveGames.setStyleSheet("color: rgb(255, 255, 255);")
        self.filterValveGames.setObjectName("filterValveGames")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 291, 251))
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255)")
        self.groupBox.setObjectName("groupBox")
        self.listGamesOwned = QtWidgets.QListView(self.centralwidget)
        self.listGamesOwned.setGeometry(QtCore.QRect(390, 30, 256, 241))
        self.listGamesOwned.setObjectName("listGamesOwned")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(420, 300, 131, 40))
        self.searchButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.searchButton.setObjectName("searchButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vapor"))
        self.searchBar.setPlaceholderText(_translate("MainWindow", "Search for Games Here"))
        self.filterButtonSpecials.setText(_translate("MainWindow", "Specials"))
        self.filterButtonScore.setText(_translate("MainWindow", "Top Score"))
        self.filterValveGames.setText(_translate("MainWindow", "Games by Valve"))
        self.groupBox.setTitle(_translate("MainWindow", "Welcome!"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
