# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Dialog(object):
    def setupUi(self, Login_Dialog):
        Login_Dialog.setObjectName("Login_Dialog")
        Login_Dialog.resize(477, 620)
        Login_Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.pEdit = QtWidgets.QLineEdit(Login_Dialog)
        self.pEdit.setGeometry(QtCore.QRect(200, 340, 181, 31))
        self.pEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pEdit.setObjectName("pEdit")
        self.label = QtWidgets.QLabel(Login_Dialog)
        self.label.setGeometry(QtCore.QRect(80, 250, 311, 20))
        self.label.setStyleSheet("color:rgb(255, 255, 255); font-size:12pt;")
        self.label.setObjectName("label")
        self.uLabel = QtWidgets.QLabel(Login_Dialog)
        self.uLabel.setGeometry(QtCore.QRect(100, 290, 91, 20))
        self.uLabel.setStyleSheet("color:rgb(255, 255, 255); font-size:15pt;")
        self.uLabel.setObjectName("uLabel")
        self.greeting = QtWidgets.QLabel(Login_Dialog)
        self.greeting.setGeometry(QtCore.QRect(150, 160, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(27)
        self.greeting.setFont(font)
        self.greeting.setStyleSheet("color:rgb(255, 255, 255);")
        self.greeting.setAlignment(QtCore.Qt.AlignCenter)
        self.greeting.setWordWrap(False)
        self.greeting.setObjectName("greeting")
        self.pLabel = QtWidgets.QLabel(Login_Dialog)
        self.pLabel.setGeometry(QtCore.QRect(100, 340, 91, 20))
        self.pLabel.setStyleSheet("color:rgb(255, 255, 255); font-size:15pt;")
        self.pLabel.setObjectName("pLabel")
        self.loginButton = QtWidgets.QPushButton(Login_Dialog)
        self.loginButton.setGeometry(QtCore.QRect(130, 440, 201, 41))
        self.loginButton.setStyleSheet("color:rgb(255, 255, 255)")
        self.loginButton.setObjectName("loginButton")
        self.uEdit = QtWidgets.QLineEdit(Login_Dialog)
        self.uEdit.setGeometry(QtCore.QRect(200, 290, 181, 31))
        self.uEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.uEdit.setObjectName("uEdit")
        self.label_2 = QtWidgets.QLabel(Login_Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 390, 121, 16))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.signUpButton = QtWidgets.QPushButton(Login_Dialog)
        self.signUpButton.setGeometry(QtCore.QRect(254, 390, 101, 23))
        self.signUpButton.setStyleSheet("color:rgb(255, 255, 255)")
        self.signUpButton.setObjectName("signUpButton")

        self.retranslateUi(Login_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Login_Dialog)

    def retranslateUi(self, Login_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Login_Dialog.setWindowTitle(_translate("Login_Dialog", "Dialog"))
        self.label.setText(_translate("Login_Dialog", "Please enter your username and password."))
        self.uLabel.setText(_translate("Login_Dialog", "Username"))
        self.greeting.setText(_translate("Login_Dialog", "Welcome!"))
        self.pLabel.setText(_translate("Login_Dialog", "Password"))
        self.loginButton.setText(_translate("Login_Dialog", "Login"))
        self.label_2.setText(_translate("Login_Dialog", "Don\'t have an account?"))
        self.signUpButton.setText(_translate("Login_Dialog", "Create Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Dialog = QtWidgets.QDialog()
    ui = Ui_Login_Dialog()
    ui.setupUi(Login_Dialog)
    Login_Dialog.show()
    sys.exit(app.exec_())
