# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(952, 700))
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54); background-image: url(C:\\Users\\patri\\source\\repos\\Python Test Programs\\GUI_TestingGrounds);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 350, 1081, 421))
        self.tableView.setStyleSheet("color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.searchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchBar.setGeometry(QtCore.QRect(10, 320, 381, 20))
        self.searchBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.searchBar.setObjectName("searchBar")
        self.filterButtonSpecials = QtWidgets.QPushButton(self.centralwidget)
        self.filterButtonSpecials.setGeometry(QtCore.QRect(400, 320, 91, 23))
        self.filterButtonSpecials.setStyleSheet("color: rgb(255, 255, 255);")
        self.filterButtonSpecials.setObjectName("filterButtonSpecials")
        self.filterButtonPositive = QtWidgets.QPushButton(self.centralwidget)
        self.filterButtonPositive.setGeometry(QtCore.QRect(500, 320, 91, 23))
        self.filterButtonPositive.setStyleSheet("color: rgb(255, 255, 255);")
        self.filterButtonPositive.setObjectName("filterButtonPositive")
        self.filterButtonNegative = QtWidgets.QPushButton(self.centralwidget)
        self.filterButtonNegative.setGeometry(QtCore.QRect(600, 320, 91, 23))
        self.filterButtonNegative.setStyleSheet("color: rgb(255, 255, 255);")
        self.filterButtonNegative.setObjectName("filterButtonNegative")
        self.filterValveGames = QtWidgets.QPushButton(self.centralwidget)
        self.filterValveGames.setGeometry(QtCore.QRect(700, 320, 91, 23))
        self.filterValveGames.setStyleSheet("color: rgb(255, 255, 255);")
        self.filterValveGames.setObjectName("filterValveGames")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 291, 251))
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255)")
        self.groupBox.setObjectName("groupBox")
        self.listGamesOwned = QtWidgets.QListView(self.centralwidget)
        self.listGamesOwned.setGeometry(QtCore.QRect(390, 30, 256, 241))
        self.listGamesOwned.setObjectName("listGamesOwned")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vapor"))
        self.searchBar.setText(_translate("MainWindow", "Search for Games Here"))
        self.filterButtonSpecials.setText(_translate("MainWindow", "Specials"))
        self.filterButtonPositive.setText(_translate("MainWindow", "Top Positive"))
        self.filterButtonNegative.setText(_translate("MainWindow", "Top Negative"))
        self.filterValveGames.setText(_translate("MainWindow", "Games by Valve"))
        self.groupBox.setTitle(_translate("MainWindow", "Welcome!"))
